// <auto-generated />
namespace EnquiryRequest3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class autotimestampenquirydateatdblevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autotimestampenquirydateatdblevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803132303066_auto timestamp enquirydate at db level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
