// <auto-generated />
namespace EnquiryRequest3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class linktoquotefrominvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linktoquotefrominvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201806080948175_link to quote from invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
