// <auto-generated />
namespace EnquiryRequest3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changestoreferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestoreferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201803092246141_changes to references"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
