// <auto-generated />
namespace EnquiryRequest3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changetoquoteacceptdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetoquoteacceptdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201806130930259_change to quote accept date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
