// <auto-generated />
namespace EnquiryRequest3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changestologinmodeltoallownonemailaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestologinmodeltoallownonemailaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201805181350075_changes to login model to allow non email address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
